development:
  adapter: postgresql
  encoding: utf8
  database: frenzy_development
  pool: 5
  username: johnvanarkelen
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: frenzy_test
  pool: 5
  username: johnvanarkelen
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: frenzy_production
  pool: 5
  username: johnvanarkelen
  password:
  host: localhost
